### ISSUE TITLE
404 after installation from Marketplace

### ISSUE THREAD

**Issue by Hyabusa1990** [InfotelGLPI/databases#14]
* Version of the plugin : 
2.3.0

* Version of your GLPI : 
9.5.1

* Steps to reproduce (which actions have you made) :
1. Install the Plugin from Marketplace
2. Activate the Plugin from Marketplace
3. Click on the Link "Inventory" --> "Databases"

* Expected result :
Page of the Database inventory

* Actual result :
404

* further information:
after I installed the Plugin, I've searched for the files on /plugins/databases there was no files but under /marketplace/databases, there was all the Files and Folders 

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/16559414/94565612-b8ca0100-0269-11eb-8f44-709cfa856218.png)

**Comment by sipmann** [comment]
Also, if you change the url to `marketplace/databases/front/database.php` the page loads but we have many database errors.

```SQL
SQL Error "1146": Table 'glpi_tiab.glpi_plugin_databases_databases' doesn't exist in query "SHOW COLUMNS FROM `glpi_plugin_databases_databases`"
```

**Comment by ales-infotel** [comment]
Hi,
Can you try again ?

**Comment by sipmann** [comment]
Just updated to version 2.3.1 and it's working. Ty
