### ISSUE TITLE
Unable to search in attached items

### ISSUE THREAD

**Issue by bacus99** [InfotelGLPI/databases#4]
When in plugin Database, unable to search in assiociated items

**Comment by tsmr** [comment]
From where ? can you add screenshots ? or describe a little more your problem ?

**Comment by bacus99** [comment]
In dropdown, no choices for Associated Items

![1](https://cloud.githubusercontent.com/assets/11425241/13157541/6dba9b6e-d656-11e5-8a54-c035592c3470.jpg)

Searching for a server named mongo0 do not provide results
![2](https://cloud.githubusercontent.com/assets/11425241/13157544/71c16972-d656-11e5-904c-77be75ca7501.jpg)

**Comment by tsmr** [comment]
I understand but plugins have not access to global search criteria like tickets for search on associated items

**Comment by bacus99** [comment]
I understand, but I may be able to search at least on what I see there?  If I see a attached server in my view, I'm usually able to search it (in dropdown or at least items seen? no?

**Comment by tsmr** [comment]
No because you can link many objects with a database, so we need use global search criteria for this
