### ISSUE TITLE
Lien entre plugins Databases et FormCreator

### ISSUE THREAD

**Issue by EC2311** [InfotelGLPI/databases#9]
Bonjour

Comment faire lien entre le plugin databases et formCreator afin que le formulaire puisse voir les objets Databases?
Faut-il modifier le plugin formCreator ou database ou les 2 ?
D'avance Merci

**Comment by keha35** [comment]
Bonjour,

La modification est a faire dans le plugin formCrator.
Après avoir regardé, les types sont chargés via les classes présentes dans formcreator/inc/fields.
Il faut donc regarder le fonctionnement a ce niveau la.

Bonne journée

**Comment by EC2311** [comment]
Bonjour,
j'ai regardé cet apm notamment en me basant sur le glpiselect. mais ceci dit, je ne vois pas trop comment réalisé cette connexion :( 
je connais les noms des tables qu'il faudrait 'lister', mais comment interfacer ?
faut-il tout ecrire en php ?

où pourrait on trouver exemple ?

D'avance merci

**Comment by keha35** [comment]
Bonjour,

Oui il s'agit d'un développement PHP.

Je vous laisse voir ça en créant une issue sur le plugin en question, ils auront probablement plus de réponse a vous apporter.
